export enum Box {
    Article = 'article',
    Blockquote = 'blockquote',
    Div = 'div',
    Fieldset = 'fieldset',
    Footer = 'footer',
    Form = 'form',
    Header = 'header',
    Hr = 'hr',
    Li = 'li',
    Main = 'main',
    Nav = 'nav',
    Ol = 'ol',
    Pre = 'pre',
    Section = 'section',
    Ul = 'ul',
}

export enum Text {
    Code = 'code',
    Div = 'div',
    H1 = 'h1',
    H2 = 'h2',
    H3 = 'h3',
    H4 = 'h4',
    H5 = 'h5',
    H6 = 'h6',
    Label = 'label',
    P = 'p',
    Span = 'span',
    Time = 'time',
}
